stan-core:
  stanPath: .stan
  excludes:
    - CHANGELOG.md
    - docs
    - package-lock.json
  imports:
    entity-client-dynamodb:
      - ../entity-client-dynamodb/.stan/interop/entity-manager-demo/**
      - ../entity-client-dynamodb/guides/stan-assistant-guide.md
    entity-manager:
      - ../entity-manager/.stan/interop/entity-manager-demo/**
      - ../entity-manager/guides/stan-assistant-guide.md
    entity-tools:
      - ../entity-tools/.stan/interop/entity-manager-demo/**
      - ../entity-tools/guides/stan-assistant-guide.md
  includes: []
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    docs:
      script: npm run docs -- --emit none
      warnPattern: ^(?!.*@smithy\\/types#ChecksumConstructor)(?!.*@smithy\\/smithy-client#DefaultsMode).*\\[warning\\]
    knip: npm run knip
